on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache docker base image build
        id: cache-docker-base-image-build
        uses: actions/cache@v3
        env:
          cache-name: cache-docker-base-image-build
        with:
          path: ./say-hello-base.tar
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./ci/Dockerfile.base') }}

      - if: ${{ steps.cache-docker-base-image-build.outputs.cache-hit != 'true' }}
        name: Docker build
        continue-on-error: true
        timeout-minutes: 30
        run: |
          docker build --file ./ci/Dockerfile.base --target say-hello-base
          docker save -o ./say-hello-base.tar say-hello-base



      - name: Checksum the "./ci" directory
        run: |
          find ./ci -type f -exec cksum {} \; | sort -k 2 > checksumResultOfDockerBuildContext.txt
      - name: Cache docker build
        id: cache-docker-build
        uses: actions/cache@v3
        env:
          cache-name: cache-docker-build
        with:
          # docker cache files are stored in `./ci` directory on Linux/macOS
          path: ./ci
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./checksumResultOfDockerBuildContext.txt') }}

      - if: ${{ steps.cache-docker-build.outputs.cache-hit != 'true' }}
        name: Docker build
        continue-on-error: true
        timeout-minutes: 30
        run: |
          docker build -t say-hello ./ci
          docker save -o ./ci/say-hello.tar say-hello

      - name: Try to run docker command
        run: |
          docker load -i ./ci/say-hello.tar
          docker run --name sayhello_3d0210 --label a5c76b --workdir /github/workspace --rm -v "/home/runner/work/practice_using_ci/practice_using_ci":"/github/workspace" say-hello  "Mona the Octocat" "This is a comment." "This is the third argument."

      # - name: Hello world action step
      #   uses: ./.github/actions/docker-build-action # Uses an action in the root directory
      #   id: hello
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      #     comments: 'This is a comment.'

      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
